### ISSUE TITLE
Data and migrations

### ISSUE THREAD

**Issue by lezhnev74** [lucid-architecture/laravel#14]
I feel like there is a lack of database migration support in Lucid.

1. There is a folder within each service called `database` where I can see `database/migration` but the data is also located in `Data` folder. How do those relate to each other?
2.  `lucid` does not have any way to make a migration (while it has a `make:model` command). Why?

**Comment by vitoo** [comment]
Did you succeed to make a migration in the src/Api/database/migration ?

Looks like` php artisan migrate && db:seed `does not looks for src/Api/database/

**Comment by nicholaschun** [comment]
Has anyone succeeded in migrating migrations in each service in Lucid?

**Comment by undjike** [comment]
@Mulkave said: You may use Laravel's php artisan migrate --path=src/Services/{service}/database/migrations/{file}.php to specify a custom path for the migration.

**Comment by Mulkave** [comment]
Thanks @undjike that is exactly how it works. It was left as such because there's an existing functionality that can achieve it, but i would be happy to provide a command that runs this in the background if it's deemed helpful such as:

```
lucid migrate <service>
```

Nevertheless, it's also been covered in [the docs](https://docs.lucidarch.dev/services/#migrations) now, thank you all for reporting!
