### ISSUE TITLE
`TypeError: this.$els.jobCodeDialog.showModal is not a function`  when viewing a Domain job code

### ISSUE THREAD

**Issue by jbalatero** [lucid-architecture/laravel#33]
## Summary
In the browser developer tools console, there is an error: `TypeError: this.$els.jobCodeDialog.showModal` when viewing a Domain job code. Viewing of code in Services and Features also does not work.

## Steps to Reproduce: 
* `composer create-project lucid-arch/laravel my-project`
* `cd my-projec`t
* `php artisan vendor:publish --provider="Lucid\Console\LucidServiceProvider"`
* In the browser, go to '/lucid/dashboard/domains' > Http > Respond With Json Error > Click the *Code.*

## Expected Result
It should display a modal showing the code of the selected Job

## Actual Result
`TypeError: this.$els.jobCodeDialog.showModal is not a function`  when viewing a Domain job code

## State
* Laravel version: 5.6
* OS: Win10
* XAMPP stack using vhost

**Comment by XavierTecBr** [comment]
I'm having the same error using firefox, but it's working on chrome

**Comment by Mulkave** [comment]
Sorry for the inconvenience, with Lucid 1.0 the dashboard has been temporarily deprecated to undergo a rework. Since you've had the curiosity to check it out, I would like to ask you:

1. What would you be using it for?
2. What is the feature you saw most beneficial?

If possible, please open a Discussion at the new repo [lucidarch/lucid](https://github.com/lucidarch/lucid/discussions) if interested in discussing further.
